apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python Test App, named ${{values.app_name}}
  annotations:
    github.com/project-slug: shiv2380/${{values.app_name}}
spec:
  type: service
  owner: development
  lifecycle: experimental